# Generated by Django 2.0.5 on 2018-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(max_length=60, verbose_name='Company full name')),
                ('tagline', models.CharField(max_length=255, verbose_name='Company tagline')),
                ('quote', models.TextField()),
                ('quote_speaker', models.CharField(default='Unkown', max_length=60, verbose_name='Featured quote speaker')),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('location', models.CharField(max_length=100, verbose_name='Location name')),
                ('subcity', models.CharField(max_length=100)),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
