# Generated by Django 2.0.5 on 2018-05-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
    ]
