# Generated by Django 2.0.5 on 2018-05-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
