# Generated by Django 2.0.5 on 2018-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180505_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='wallpaper',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
