# Generated by Django 2.0.5 on 2018-05-05 20:08

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180505_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='wallpaper',
            field=models.ImageField(upload_to=pages.models.service_wallpaper_path),
        ),
    ]
