# Generated by Django 2.0.5 on 2018-05-05 21:42

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180506_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('wallpaper', models.ImageField(upload_to=pages.models.service_wallpaper_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
