# Generated by Django 2.0.5 on 2018-05-05 21:43

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180506_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='wallpaper',
            field=models.ImageField(height_field=960, upload_to=pages.models.slide_path, width_field=1440),
        ),
    ]
