# Generated by Django 2.0.5 on 2018-05-06 07:53

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20180506_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField(verbose_name='Short bio')),
                ('avatar', models.ImageField(blank=True, upload_to=pages.models.staff_avatar_path)),
                ('cv', models.FileField(blank=True, upload_to=pages.models.staff_cv_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True, help_text='Short description with less than 255 letters.', max_length=255),
        ),
        migrations.AlterField(
            model_name='slide',
            name='wallpaper',
            field=models.ImageField(help_text='Upload a 1440x960 pixel .jpg image.', upload_to=pages.models.slide_path),
        ),
    ]
