# Generated by Django 2.0.5 on 2018-05-05 21:45

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20180506_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='wallpaper',
            field=models.ImageField(upload_to=pages.models.service_wallpaper_path),
        ),
    ]
