# Generated by Django 2.0.5 on 2018-05-05 21:51

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20180506_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True, help_text='Short description with less than 255 letters.', max_length=255),
        ),
        migrations.AlterField(
            model_name='slide',
            name='wallpaper',
            field=models.ImageField(help_text='Upload a 1440x960 pixel .jpg image.', upload_to=pages.models.service_wallpaper_path),
        ),
    ]
