# Generated by Django 2.0.5 on 2018-05-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20180506_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='team_description',
            field=models.TextField(default='', verbose_name='Short team description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='description1',
            field=models.TextField(verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description2',
            field=models.TextField(verbose_name='More company description'),
        ),
    ]
