# Generated by Django 2.0.5 on 2018-05-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20180506_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='icons',
            new_name='icon',
        ),
    ]
