# Generated by Django 2.0.5 on 2018-05-10 07:27

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20180506_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a 360x360 pixel .jpg image.', upload_to=pages.models.staff_avatar_path),
        ),
    ]
