# Generated by Django 2.0.5 on 2018-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20180510_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload 100x69 pixels trasparent PNG image file.', null=True, upload_to='static/img/logo/', verbose_name='Logo (Destop)'),
        ),
    ]
