# Generated by Django 2.0.5 on 2018-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_hover',
            field=models.ImageField(blank=True, help_text='Upload 100x69 pixels trasparent PNG image file.', null=True, upload_to='static/img/logo/', verbose_name='Logo on hover'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_mobile',
            field=models.ImageField(blank=True, help_text='Upload 597x412 pixels trasparent PNG image file.', null=True, upload_to='static/img/logo/', verbose_name='Logo on hover'),
        ),
    ]
