# Generated by Django 2.0.5 on 2018-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20180513_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_mobile',
            field=models.ImageField(blank=True, help_text='Upload 597x412 pixels trasparent PNG image file.', null=True, upload_to='static/img/logo/', verbose_name='Logo for mobile'),
        ),
    ]
