# Generated by Django 2.0.5 on 2018-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20180513_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload 100x69 pixels trasparent PNG image file.', null=True, upload_to='static/img/logo/', verbose_name='Logo (Desktop)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_hover',
            field=models.ImageField(blank=True, help_text='Upload 100x69 pixels trasparent PNG image file.', null=True, upload_to='static/img/logo/', verbose_name='Logo on hover (Desktop)'),
        ),
    ]
