# Generated by Django 2.0.5 on 2018-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20180513_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload 100x69 pixels trasparent PNG image file.', null=True, upload_to='logo/', verbose_name='Logo (Desktop)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_hover',
            field=models.ImageField(blank=True, help_text='Upload 100x69 pixels trasparent PNG image file.', null=True, upload_to='logo/', verbose_name='Logo on hover (Desktop)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_mobile',
            field=models.ImageField(blank=True, help_text='Upload 597x412 pixels trasparent PNG image file.', null=True, upload_to='logo/', verbose_name='Logo for mobile'),
        ),
    ]
