# Generated by Django 2.0.5 on 2018-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20180513_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fevicon',
            field=models.ImageField(blank=True, help_text='Upload 23x16 pixels 23x16 pixels .ico icon file.', null=True, upload_to='fevicon/', verbose_name='Fevicon (Title Icon)'),
        ),
    ]
