# Generated by Django 2.0.5 on 2018-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20180515_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
