name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: True
  ALLOWED_HOSTS: .localhost, .127.0.0.1
jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install Python Dependencies
        run: python -m pip install -r requirements.txt
      - name: Run Tests
        run: python manage.py test --verbosity 3
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
     - build
    steps:
    - uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd "${{ secrets.WORK_DIR }}"
          git checkout "${{ secrets.RELEASE_BRANCH }}"
          git add . && git stash && && git pull
          source venv/bin/activate
          python -m pip install -r requirements.txt
          python manage.py migrate --no-input
          python manage.py collectstatic --no-input
          deactivate
          git stash clear
          systemctl restart rekikeng
    - name: Delete SSH key
      run: rm -rf ~/.ssh
